name: Rebuild fleuron.study

on:
  release:
    types: [published]

jobs:
  deploy:
    uses: wilsonhyeh/fleuron-site/.github/workflows/deploy.yml@main
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
